<html>
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="<?= PATH ?>/" class="brand-link">
    <i class="bi bi-house"></i>
    <span class="brand-text font-weight-light">Intelli Food</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <br>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="bi bi-list"></i>
            <p>
              Pedidos
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="<?= PATH ?>/meus-pedidos" class="nav-link">
                <i class="bi bi-list-ul"></i>
                <p>Meus Pedidos</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="<?= PATH ?>/cardapio" class="nav-link">
                <i class="bi bi-plus-circle-dotted"></i>
                <p>Novo Pedido</p>
              </a>
            </li>

            </a>
        </li>
      </ul>
      </li>

      <li class="nav-item">
        <a href="#" class="nav-link">
          <i class="bi bi-house-door"></i>
          <p>
            Endereços
            <i class="right fas fa-angle-left"></i>
          </p>
        </a>
        <ul class="nav nav-treeview">
          <li class="nav-item">
            <a href="<?= PATH ?>/enderecos" class="nav-link">
              <i class="bi bi-list-check"></i>
              <p>Meus Endereços</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<?= PATH ?>/cadastrar-endereco" class="nav-link">
              <i class="bi bi-plus-circle-dotted"></i>
              <p>Adicionar Endereço</p>
            </a>

        </ul>
      </li>
      <li class="nav-item">
        <a href="<?= PATH ?>/cardapio" class="nav-link">
          <i class="bi bi-list-ul"></i>
          <p>Cardápio</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="<?= PATH ?>/carrinho" class="nav-link">
          <i class="bi bi-cart"></i>
          <p>Carrinho</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="<?= PATH ?>/logout" class="nav-link">
          <i class="bi bi-box-arrow-left"></i>
          <p>Logout</p>
        </a>
      </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

</html>