<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Intelli Food</title>
 
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/dist/css/adminlte.min.css">
</head>


<body class="hold-transition register-page">
<div class="register-box">
  <div class="card card-outline card-primary ">
    <div class="card-header text-center">
      <a href="<?= PATH ?>" class="h1"><b>Intelli</b>Food</a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Cadastre-se</p>

      <form action="<?= PATH ?>/cadastro" method="post">
        <div class="input-group mb-3">

            <div class="input-group mb-3">
            <input type="text" name="cpf" class="form-control" placeholder="CPF" required="required">
            <div class="input-group-append">
            <div class="input-group-text">
                <span class="fas fa-asterisk"></span>
            </div>
            </div>
        </div>

          <input type="text" name="nome" class="form-control" placeholder="Nome" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>

        <div class="input-group mb-3">
          <input type="text" name="telefone" class="form-control" placeholder="Telefone" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-phone"></span>
              
            </div>
          </div>
        </div>

        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Email" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>

        <div class="input-group mb-3">
          <input type="password" name="senha" class="form-control" placeholder="Senha" required="required">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>

      
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
          </div>
          <!-- /.col -->
        
        </div>
      </form>

      <a href="<?= PATH ?>/login" class="text-center">Já possui uma conta? Fazer login</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="<?= PATH_ADMIN ?>/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?= PATH_ADMIN ?>/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="<?= PATH_ADMIN ?>/dist/js/adminlte.min.js"></script>

</body>
</html>
