<?php 
if (!isset($_SESSION)) session_start();
if (!isset($_SESSION['loggedIn']) || $_SESSION['loggedIn'] !== true) {
  session_destroy(); 
  header('Location: /login');
  exit;
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Intelli Food</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="<?= PATH ?>/home" class="nav-link">Home</a>
      </li>
    
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
     

     
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
     
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <?php 
  include('includes/navbarCliente.phtml')
  ?>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Carrinho</h1>
            
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?= PATH ?>/home">Home</a></li>
              
              <li class="breadcrumb-item active">Carrinho</li>
              
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>


    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            
            <div class="card card-navy">
              <div class="card-header">
                <h3><b>Seu Carrinho</b></h3>
                <?php $total_parcial = 0?>
              </div>
              <!-- Lanches -->
              <div class="card-body">
              <table class="table table-bordered table-hover">
                    <tr>
                        <th>Lanche</th>
                        <th width='150px'>Preço</th>
                        <th width='150px'>Ações</th>                
                    </tr>
                        <?php
                            if (isset($lanche)){
                                foreach ($lanche as $item){ 
                                  $total_parcial = $total_parcial + $item->preco;
                                ?>
                                    <tr>
                                        <td><?= $item->lanche?></td> 
                                        <td>R$<?= $item->preco?></td> 
                                        <td><a href="<?= PATH ?>/remover-lanche?idlanche=<?= $item->idlanche ?>"><button class="btn btn-danger">Remover Item</button></a></td>
                                    </tr>
                                <?php
                                }
                            }
                        ?>
                </table>
              </div>
              <!-- Porções -->
              <div class="card-body">
              <table class="table table-bordered table-hover">
                    <tr>
                        <th>Porções</th>
                        <th width='150px'>Preço</th>
                        <th width='150px'>Ações</th>                
                    </tr>
                        <?php
                            if (isset($porcao)){
                                foreach ($porcao as $item){
                                  $total_parcial = $total_parcial + $item->preco;
                                ?>
                                    <tr>
                                        <td><?= $item->porcao?></td>
                                        <td>R$<?= $item->preco?></td>  
                                        <td><a href="<?= PATH ?>/remover-porcao?idporcao=<?= $item->idporcao ?>"><button class="btn btn-danger">Remover Item</button></a></td>
                                    </tr>
                                <?php
                                }
                            }
                        ?>
                </table>
              </div>
              <!-- Bebidas -->
              <div class="card-body">
              <table class="table table-bordered table-hover">
                    <tr>
                      <th>Bebida</th>
                      <th width='150px'>Preço</th>
                      <th width='150px'>Ações</th>                
                    </tr>
                        <?php
                            if (isset($bebida)){
                                foreach ($bebida as $item){
                                  $total_parcial = $total_parcial + $item->preco;
                                ?>
                                    <tr>
                                        <td><?= $item->bebida?></td>
                                        <td>R$<?= $item->preco?></td> 
                                        <td><a href="<?= PATH ?>/remover-bebida?idbebida=<?= $item->idbebida ?>"><button class="btn btn-danger">Remover Item</button></a></td>
                                    </tr>
                                <?php
                                } 
                            }
                        ?>
                </table>
                <br>
                <table class="table table-bordered table-hover">
                    <tr>
                      <th width='130px'>Total Parcial:</th>
                      <th ><?php echo "R$: ", $total_parcial?></th>

                     
                     <?php $_SESSION['total'] = $total_parcial; ?>
                     <th width='160px'><a href="<?= PATH ?>/finalizar-pedido"><button type="submit" class="btn btn-success">Finalizar Pedido</button></a></th>         
                      

                      
                      
                    </tr>    
                </table>
                
              </div>
              
              <!-- /.card-body -->
              <!-- /.card-footer-->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <?php 
  include('includes/footer.phtml')
  ?>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="<?= PATH_ADMIN ?>/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?= PATH_ADMIN ?>/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- overlayScrollbars -->
<script src="<?= PATH_ADMIN ?>/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="<?= PATH_ADMIN ?>/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
</body>
</html>
