<?php 
if (!isset($_SESSION)) session_start();
if (!isset($_SESSION['loggedIn']) || $_SESSION['loggedIn'] !== true) {
  session_destroy(); 
  header('Location: /login');
  exit;
}

if ($_SESSION['nivel'] >= 4) {    
  header('Location: /home');
  exit;
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Intelli Food</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/fontawesome-free/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="<?= PATH ?>/admin" class="nav-link">Admin</a>
      </li>
    
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
     

     
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <?php 
  include('includes/navbarADM.phtml')
  ?>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Detalhes - Pedido</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<?= PATH ?>/admin">Admin</a></li>
              
              <li class="breadcrumb-item active">Detalhes - Pedido</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>



    <!-- Main content -->
    <section class="content">

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-body">

              <?php if (isset($success)): ?>
                <div class="alert alert-success"><?= isset($success) ? $success : '' ?></div>
            <?php endif; ?>
            
              <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>Lanches</th>
                        
                    </tr> 

                    
                    <?php

                    if (isset($lanches)){
                        foreach ($lanches as $lanche){
                            ?>
                           <tr>
                                <td><?= $lanche->lanche ?> </td>
                           </tr>
                            <?php
                        }
                    }
                    ?>
                    

                    
                </table>
              </div>
              <div class="card-body">

                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        
                        <th>Porções</th>
                        
                    </tr> 

              
                    <?php
                    if (isset($porcoes)){
                        foreach ($porcoes as $porcao){
                            ?>
                            <tr>
                                <td><?= $porcao->porcao ?> </td>
                            </tr>
                            <?php
                        }
                    }
                    ?>
                    

                    
                </table>
              </div>
              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                    
                        <th>Bebidas</th>
                        
                    </tr> 

            
                    
                    <?php
                    if (isset($bebidas)){
                        foreach ($bebidas as $bebida){
                            ?>
                            <tr>
                                <td><?= $bebida->bebida ?> </td>
                           </tr>
                            <?php
                        }
                    }

                    ?> 
                    
                </table>
                
              </div>

              <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>Endereço</th>
                        <th>Preço total</th>
                    </tr> 

                    <?php
                    if (isset($pedido)){
                        foreach ($pedido as $pedido){
                            ?>
                            <tr>
                                <td><?= $pedido->ende ?> </td>
                                <td>R$<?= $pedido->preco ?> </td>
                           </tr>
                            <?php
                        }
                    }

                    ?> 
                </table>
                
              </div>
              <!-- /.card-body -->
              <!-- /.card-footer-->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->



  
  <?php 
  include('includes/footer.phtml')
  ?>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="<?= PATH_ADMIN ?>/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?= PATH_ADMIN ?>/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- overlayScrollbars -->
<script src="<?= PATH_ADMIN ?>/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="<?= PATH_ADMIN ?>/dist/js/adminlte.min.js"></script>

</body>
</html>
