<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Intelli Food</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/fontawesome-free/css/all.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?= PATH_ADMIN ?>/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="<?= PATH ?>" class="h1"><b>Intelli</b>Food</a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Realize seu login</p>
            <?php if (isset($success)): ?>
                <div class="alert alert-success"><?= isset($success) ? $success : '' ?></div>
            <?php endif; ?>
            <?php if (isset($warning)): ?>
                <div class="alert alert-warning"><?= isset($warning) ? $warning : '' ?></div>
            <?php endif; ?>
            <?php if (isset($erro)): ?>
                <div class="alert alert-danger"><?= isset($erro) ? $erro : '' ?></div>
            <?php endif; ?>
            
      <form action="<?= PATH ?>/login" method="post">
        <div class="input-group mb-3">
          <input type="email" class="form-control" name="email" placeholder="Email" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" name="senha" placeholder="Senha" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Login</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

   <!-- /.card-body 
      <p class="mb-1">
        <a href="forgot-password.html">Esqueci minha senha</a>
        </p>
     -->
      <p class="mb-0">
        <a href="<?= PATH ?>/cadastro" class="text-center">Registrar-se</a>
      </p>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="<?= PATH_ADMIN ?>/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?= PATH_ADMIN ?>/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="<?= PATH_ADMIN ?>/dist/js/adminlte.min.js"></script>
</body>
</html>
